### ISSUE TITLE
Setup build process with cime_config

### ISSUE THREAD

**Issue by jimmielin** [ESCOMP/HEMCO_CESM#1]
**Task description:** Setup building `HEMCO_CESM` within CAM with `cime_config`.

Notes here: https://github.com/ESMCI/cime/wiki/Managing-externals-included-in-CIME

**Comment by gold2718** [comment]
A note on what build files are required to add a new component in in the [CIME manual](https://esmci.github.io/cime/):
https://esmci.github.io/cime/build_cpl/adding-components.html

**Comment by jimmielin** [comment]
* I've updated my `jimmielin/CAM` fork `feature/hemco` with code that loads `jimmielin/HEMCO_CESM` as an external (using my fork for now during development). See https://github.com/jimmielin/CAM/commits/feature/hemco
* `ESCOMP/HEMCO_CESM` also includes `Externals_HCO.cfg` which will load `dev/3.0.0-cesm` branch from the official HEMCO repository. See https://github.com/jimmielin/HEMCO_CESM/blob/development/Externals_HCO.cfg

I am working on making the main HEMCO source code repository buildable along with CAM. There are preprocessor variables and some kinks to work out as HEMCO was not designed to build outside GEOS-Chem/GEOS-5 yet. Changes in the main HEMCO repo's `dev/3.0.0-cesm` branch will add CESM-specific code (`use PIO` etc.) under the C-preprocessor switches added in CAM's `bld/configure` when building with HEMCO option enabled:

` -DMODEL_ -DMODEL_CESM -DHEMCO_CESM `

**Comment by jimmielin** [comment]
Noting here that HEMCO right now builds in CAM through hard-coded subdirs like everyone else. This solution is OK for now but we will add more subdirs later as HEMCO 3.0 progresses. If possible it'd be great if the build process could call the CMake in HEMCO right now and hand off the HEMCO compile process to the external lib so we don't maintain a hardcoded list of HEMCO source directories in `bld/configure`. What do you think? @gold2718 

Also shared libs used by HEMCO (date time stuff) that are also present in GEOS-Chem may conflict when compiled with CESM-GC. Probably have to coordinate with Thibaud on recognizing `if ($chem_pkg eq 'geoschem') {`.

```perl
    if ($hemco) {
        print $fh "$camsrcdir/src/hemco\n";

        # hplin 2/16/20: temporarily add hemco src code directories manually
        # until we figure out a better compile routine.
        print $fh "$camsrcdir/src/hemco/src/Core\n";
        print $fh "$camsrcdir/src/hemco/src/Extensions\n";
        print $fh "$camsrcdir/src/hemco/src/Interfaces\n";

        # if not compiling with GEOS-Chem; coordinate this with tfritz later
        # we may eventually remove all this
        print $fh "$camsrcdir/src/hemco/src/Shared\n";
    }
```
