### ISSUE TITLE
Create GridComp and run from CAM

### ISSUE THREAD

**Issue by jimmielin** [ESCOMP/HEMCO_CESM#2]
## Task description:
* Create a HEMCO GridComp with initialization, run, final methods to perform tasks attached below. ("HEMCAM" interface)
* Run the init/run/final routines from within CAM at specified time steps

### Initialization
Import from CAM
* Species data (name, molecular weights) 
* ESMF Mesh
* HEMCO Grid (lat, lon array, pass levels as dummy)

Compute regridding handles for HEMCO's Grid `HcoState%Grid%ESMFGrid` (type `ESMF_Grid`) to the mesh received `ESMF_Mesh`, in two directions.

### Run
Import from CAM
* Clock
* `State%Q`, `cam_in%cflx`
* Meteorology (check met fields that we need)
* Vertical levels (geopotential height, box height, temperature)
[From CAM: there is state%zm, %zi]

Note: data is passed in from physics state. Use init-generated regridding handles to map from `ESMF_Mesh` to `ESMF_Grid`.

Update HEMCO internals

```fortran
call HEMCO_Chunk_Run( clock, state, cam_in, state%zm, state%zi, ... met fields? )
```
Arguments list to be discussed later.

### GetField
Export fields from HEMCO internal state (HcoState%Val(ID)%....) and write them to a given function **with remapping to physics state**. e.g.

```fortran
! call HEMCO_Get_Field( FieldName, TargetArray )
 REAL(f4) :: emissions_NO(ncol, pver)
 call HEMCO_Get_Field( 'NO', emissions_NO )
```

### Final
Release memory

**Comment by gold2718** [comment]
A (somewhat messy) example that works in CESM2 is at https://github.com/gold2718/CAM/tree/ionos_coupling
See src/ionosphere/waccmx/edyn_esmf.F90

**Comment by jimmielin** [comment]
Most of the framework for this has been set up in `src/hemco/hemco_interface.F90`.
Specific tasks for working will be added in a more detailed issue, closing this.
